#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Copyright (C) 2012-2013 Antoine Beaupré <anarcat@orangeseeds.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os

directory, basename = os.path.split(sys.argv[0])

if basename == 'msign-cli':
    from monkeysign.cli import MonkeysignCli as ui
else:
    try:
        from monkeysign.gtkui import MonkeysignScanUi as ui
    except (ImportError):
        print "some modules missing for scanning functionality, going commandline-only"
        from monkeysign.cli import MonkeysignCli as ui

with ui() as u:
    u.main()
