#!/usr/bin/env python

from monkeysign.gtkui import MonkeysignScanUi

if __name__ == '__main__':
        (options, args) = MonkeysignScanUi.parse_args()
        # we ignore the key passed on the commandline
        MonkeysignScanUi(None, options)
