#!/usr/bin/env python

import sys
import os

p, m = os.path.split(sys.argv[0])

if m == 'msign-cli':
    from monkeysign.cli import MonkeysignCli as ui
else:
    try:
        from monkeysign.gtkui import MonkeysignScanUi as ui
    except (ImportError):
        print "some modules missing for scanning functionality, going commandline-only"
        from monkeysign.cli import MonkeysignCli as ui

with ui() as u:
    u.main()
